### ISSUE TITLE
Camera behavior

### ISSUE THREAD

**Issue by deadletterb** [mdaquin/3d_graph_layout_unity#2]
I have a stripped down unity fresh install running your project. 

Unity install - 2020.2.1f1

Notes - 
First, there's a typo in graph.cs - height is mispelled as heigth and length is misspelled as lenght

Second, when you first load the files, you have to go through all of the objects and assign the script - graph.cs, and node.cs for the different prefabs. should I have to do that? 

Third, when I press play on the game and the (working) graph.cs script runs, the camera seems to be in the middle of the pack. Have I not set something correctly to make it stay out of the pack and look back into the center? here's a video of the behavior. Note that I sped up the camera so I could watch it adjust faster. 

In some of the times I installed it, notably 2021, it said there was a problem with Camera.cs having the same name as an existing object?

https://user-images.githubusercontent.com/40750668/103164574-149d1b00-47c2-11eb-8106-a3579c7105ce.mp4

**Comment by mdaquin** [comment]
Thanks for the comments. This was not extensively tested outside of my own set up as it is only a demo to demonstrate a concept. 
I will correct the typos ASAP.
About having to re-assign the scripts to the objects, that should not happen. I will check if there is not something missing.
About Camera.cs having the same name as another object, I haven't seen this before. I will test on 2021.
Regarding the placement of the camera, it has a rather simple behaviour, which could certainly be improved:
   - It will always point towards the centre of the graph (average position of all nodes)
   - It moves along the z axis using the up and down arrow keys 
You can also change the initial position of the camera in the editor. if your graph is large, I would suggest a large negative value for the initial z position.

**Comment by mdaquin** [comment]
I have now corrected the typos.
The paths to resources (materials, scripts, etc.) get lost depending on how you import things. It is unfortunate but you have to add everything, including the camera script and the link to the graph for the camera.
Only tested on 2020.1.0f1
